services:
  credit:
    build: ./credit
    container_name: credit
    depends_on:
      - postgres
      - customer
      - product
    ports:
      - "8081:8081"
    networks:
      - postgres

  customer:
    build: ./customer
    container_name: customer
    depends_on:
      - postgres
    ports:
      - "8082:8082"
    networks:
      - postgres

  product:
    build: ./product
    container_name: product
    depends_on:
      - postgres
    ports:
      - "8083:8083"
    networks:
      - postgres

  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: sebastian
      POSTGRES_PASSWORD: password
      POSTGRES_MULTIPLE_DATABASES: credit,product,customer
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
      - ./pg-init-scripts:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres:
    driver: bridge

volumes:
  postgres:

